[package]
name = "playwright"
version = "0.1.0"
license = "MIT"
authors = ["octaltree <octaltree@gmail.com>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = { version = "2.0.2", optional = true }
async-std = { version = "1.9.0", optional = true }
tokio = { version = "1.2.0", optional = true }
zip = "0.5.10"

[build-dependencies]
reqwest = { version = "0.11.1", features = ["blocking"] }

[features]
runtime-actix = ["actix-rt"]
runtime-async-std = ["async-std"]
runtime-tokio = ["tokio"]
