[package]
name = "playwright"
version = "0.1.0"
license = "MIT"
authors = ["octaltree <octaltree@gmail.com>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.13"
log = "0.4.14"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.63"
zip = "0.5.10"
strong = { version = "0.3.2", features = ["serde", "shorthand"] }
thiserror = "1.0.24"
downcast-rs = "1.2.0"

[build-dependencies]
reqwest = { version = "0.11.1", features = ["blocking"] }

[dev-dependencies]
env_logger = "0.8.3"
actix-rt = "2.0.2"
async-std = { version = "1.9.0", features = ["attributes"] }
tokio = { version = "1.2.0", features = ["macros"] }
